# Generated by Django 6.0.1 on 2026-02-03 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, help_text='Temperature in °C', max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, help_text='Humidity in %', max_digits=5)),
                ('pressure', models.DecimalField(decimal_places=2, help_text='Pressure in PA', max_digits=7)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
