# Generated by Django 6.0.1 on 2026-02-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='humidity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Humidity in %', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='pressure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pressure in PA', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temperature in °C', max_digits=5, null=True),
        ),
    ]
