# Generated by Django 6.0.1 on 2026-02-06 07:15

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_sensordata_humidity_alter_sensordata_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(default=app1.models.get_est_time),
        ),
    ]
